# Generated by Django 4.0.4 on 2022-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
